package com.rest.persistence.model;
// Generated 25/03/2018 05:56:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "test")
public class Course implements java.io.Serializable {

    private Long idCourse;
    private String courseName;
    private String description;
    private String prerequisite;
    private Short numberOfHours;
    private String courseCode;
    private Short courseType;
    private String userCreated;
    private Date dateCreated;
    private Byte status;
    private Set enrollmentdetails = new HashSet(0);
    private Set coursetopics = new HashSet(0);

    public Course() {
    }

    public Course(String courseName, String description, String prerequisite, Short numberOfHours, String courseCode, Short courseType, String userCreated, Date dateCreated, Byte status, Set enrollmentdetails, Set coursetopics) {
        this.courseName = courseName;
        this.description = description;
        this.prerequisite = prerequisite;
        this.numberOfHours = numberOfHours;
        this.courseCode = courseCode;
        this.courseType = courseType;
        this.userCreated = userCreated;
        this.dateCreated = dateCreated;
        this.status = status;
        this.enrollmentdetails = enrollmentdetails;
        this.coursetopics = coursetopics;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idCourse", unique = true, nullable = false)
    public Long getIdCourse() {
        return this.idCourse;
    }

    public void setIdCourse(Long idCourse) {
        this.idCourse = idCourse;
    }

    @Column(name = "courseName", length = 100)
    public String getCourseName() {
        return this.courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @Column(name = "description", length = 500)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "prerequisite", length = 65535)
    public String getPrerequisite() {
        return this.prerequisite;
    }

    public void setPrerequisite(String prerequisite) {
        this.prerequisite = prerequisite;
    }

    @Column(name = "numberOfHours")
    public Short getNumberOfHours() {
        return this.numberOfHours;
    }

    public void setNumberOfHours(Short numberOfHours) {
        this.numberOfHours = numberOfHours;
    }

    @Column(name = "courseCode", length = 10)
    public String getCourseCode() {
        return this.courseCode;
    }

    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }

    @Column(name = "courseType")
    public Short getCourseType() {
        return this.courseType;
    }

    public void setCourseType(Short courseType) {
        this.courseType = courseType;
    }

    @Column(name = "userCreated", length = 100)
    public String getUserCreated() {
        return this.userCreated;
    }

    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "dateCreated", length = 19)
    public Date getDateCreated() {
        return this.dateCreated;
    }

    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    @Column(name = "status")
    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    public Set getEnrollmentdetails() {
        return this.enrollmentdetails;
    }

    public void setEnrollmentdetails(Set enrollmentdetails) {
        this.enrollmentdetails = enrollmentdetails;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
    public Set getCoursetopics() {
        return this.coursetopics;
    }

    public void setCoursetopics(Set coursetopics) {
        this.coursetopics = coursetopics;
    }

}
