package com.rest.persistence.model;
// Generated 30/03/2018 04:43:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enrollmentdetail generated by hbm2java
 */
@Entity
@Table(name="enrollmentdetail"
    ,catalog="test"
)
public class Enrollmentdetail  implements java.io.Serializable {


     private Long idEnrollmentDetail;
     private Course course;
     private Enrollment enrollment;
     private Professor professor;
     private Date startDate;
     private Date endDate;
     private String userCreated;
     private Date dateCreated;
     private Byte status;
     private Set<Enrollmentcourseclass> enrollmentcourseclasses = new HashSet<Enrollmentcourseclass>(0);
     private Set<Enrollmentdetailschedule> enrollmentdetailschedules = new HashSet<Enrollmentdetailschedule>(0);
     private Set<Grade> grades = new HashSet<Grade>(0);

    public Enrollmentdetail() {
    }

    public Enrollmentdetail(Course course, Enrollment enrollment, Professor professor, Date startDate, Date endDate, String userCreated, Date dateCreated, Byte status, Set<Enrollmentcourseclass> enrollmentcourseclasses, Set<Enrollmentdetailschedule> enrollmentdetailschedules, Set<Grade> grades) {
       this.course = course;
       this.enrollment = enrollment;
       this.professor = professor;
       this.startDate = startDate;
       this.endDate = endDate;
       this.userCreated = userCreated;
       this.dateCreated = dateCreated;
       this.status = status;
       this.enrollmentcourseclasses = enrollmentcourseclasses;
       this.enrollmentdetailschedules = enrollmentdetailschedules;
       this.grades = grades;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEnrollmentDetail", unique=true, nullable=false)
    public Long getIdEnrollmentDetail() {
        return this.idEnrollmentDetail;
    }
    
    public void setIdEnrollmentDetail(Long idEnrollmentDetail) {
        this.idEnrollmentDetail = idEnrollmentDetail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCourse")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEnrollment")
    public Enrollment getEnrollment() {
        return this.enrollment;
    }
    
    public void setEnrollment(Enrollment enrollment) {
        this.enrollment = enrollment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProfessor")
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="startDate", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="endDate", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="userCreated", length=100)
    public String getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreated", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enrollmentdetail")
    public Set<Enrollmentcourseclass> getEnrollmentcourseclasses() {
        return this.enrollmentcourseclasses;
    }
    
    public void setEnrollmentcourseclasses(Set<Enrollmentcourseclass> enrollmentcourseclasses) {
        this.enrollmentcourseclasses = enrollmentcourseclasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enrollmentdetail")
    public Set<Enrollmentdetailschedule> getEnrollmentdetailschedules() {
        return this.enrollmentdetailschedules;
    }
    
    public void setEnrollmentdetailschedules(Set<Enrollmentdetailschedule> enrollmentdetailschedules) {
        this.enrollmentdetailschedules = enrollmentdetailschedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enrollmentdetail")
    public Set<Grade> getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }




}


