package com.rest.persistence.model;
// Generated 25/03/2018 05:56:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="service"
    ,catalog="test"
)
public class Service  implements java.io.Serializable {


     private Long idService;
     private String serviceName;
     private String goal;
     private Short customerType;
     private Short modalityType;
     private String components;
     private Short serviceType;
     private String contact;
     private String description;
     private String userCreated;
     private Date dateCreated;
     private Byte status;
     private Set enrollments = new HashSet(0);

    public Service() {
    }

    public Service(String serviceName, String goal, Short customerType, Short modalityType, String components, Short serviceType, String contact, String description, String userCreated, Date dateCreated, Byte status, Set enrollments) {
       this.serviceName = serviceName;
       this.goal = goal;
       this.customerType = customerType;
       this.modalityType = modalityType;
       this.components = components;
       this.serviceType = serviceType;
       this.contact = contact;
       this.description = description;
       this.userCreated = userCreated;
       this.dateCreated = dateCreated;
       this.status = status;
       this.enrollments = enrollments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idService", unique=true, nullable=false)
    public Long getIdService() {
        return this.idService;
    }
    
    public void setIdService(Long idService) {
        this.idService = idService;
    }

    
    @Column(name="serviceName", length=100)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    
    @Column(name="goal", length=65535)
    public String getGoal() {
        return this.goal;
    }
    
    public void setGoal(String goal) {
        this.goal = goal;
    }

    
    @Column(name="customerType")
    public Short getCustomerType() {
        return this.customerType;
    }
    
    public void setCustomerType(Short customerType) {
        this.customerType = customerType;
    }

    
    @Column(name="modalityType")
    public Short getModalityType() {
        return this.modalityType;
    }
    
    public void setModalityType(Short modalityType) {
        this.modalityType = modalityType;
    }

    
    @Column(name="components", length=65535)
    public String getComponents() {
        return this.components;
    }
    
    public void setComponents(String components) {
        this.components = components;
    }

    
    @Column(name="serviceType")
    public Short getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(Short serviceType) {
        this.serviceType = serviceType;
    }

    
    @Column(name="contact", length=65535)
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="userCreated", length=100)
    public String getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreated", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set getEnrollments() {
        return this.enrollments;
    }
    
    public void setEnrollments(Set enrollments) {
        this.enrollments = enrollments;
    }




}


