package com.rest.persistence.model;
// Generated 30/03/2018 04:43:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="test"
)
public class Student  implements java.io.Serializable {


     private Long idStudent;
     private String firstName;
     private String lastName;
     private Date birthDate;
     private Byte gender;
     private String emailAddress;
     private String userCreated;
     private Date dateCreated;
     private Byte status;
     private Set<Enrollment> enrollments = new HashSet<Enrollment>(0);
     private Set<Studentaddress> studentaddresses = new HashSet<Studentaddress>(0);

    public Student() {
    }

    public Student(String firstName, String lastName, Date birthDate, Byte gender, String emailAddress, String userCreated, Date dateCreated, Byte status, Set<Enrollment> enrollments, Set<Studentaddress> studentaddresses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.birthDate = birthDate;
       this.gender = gender;
       this.emailAddress = emailAddress;
       this.userCreated = userCreated;
       this.dateCreated = dateCreated;
       this.status = status;
       this.enrollments = enrollments;
       this.studentaddresses = studentaddresses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idStudent", unique=true, nullable=false)
    public Long getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(Long idStudent) {
        this.idStudent = idStudent;
    }

    
    @Column(name="firstName", length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="birthDate", length=19)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="gender")
    public Byte getGender() {
        return this.gender;
    }
    
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    
    @Column(name="emailAddress", length=100)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="userCreated", length=100)
    public String getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreated", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Enrollment> getEnrollments() {
        return this.enrollments;
    }
    
    public void setEnrollments(Set<Enrollment> enrollments) {
        this.enrollments = enrollments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set<Studentaddress> getStudentaddresses() {
        return this.studentaddresses;
    }
    
    public void setStudentaddresses(Set<Studentaddress> studentaddresses) {
        this.studentaddresses = studentaddresses;
    }




}


