package com.rest.persistence.model;
// Generated 25/03/2018 05:56:17 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Studentaddress generated by hbm2java
 */
@Entity
@Table(name="studentaddress"
    ,catalog="test"
)
public class Studentaddress  implements java.io.Serializable {


     private Long idStudentAddress;
     private Student student;
     private String addressName;
     private String address;
     private Short addressType;
     private Short addressNumber;
     private Short apartment;
     private String additionalInformation;
     private String reference;
     private Integer idDistrict;
     private String userCreated;
     private Date dateCreated;
     private Byte status;

    public Studentaddress() {
    }

    public Studentaddress(Student student, String addressName, String address, Short addressType, Short addressNumber, Short apartment, String additionalInformation, String reference, Integer idDistrict, String userCreated, Date dateCreated, Byte status) {
       this.student = student;
       this.addressName = addressName;
       this.address = address;
       this.addressType = addressType;
       this.addressNumber = addressNumber;
       this.apartment = apartment;
       this.additionalInformation = additionalInformation;
       this.reference = reference;
       this.idDistrict = idDistrict;
       this.userCreated = userCreated;
       this.dateCreated = dateCreated;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idStudentAddress", unique=true, nullable=false)
    public Long getIdStudentAddress() {
        return this.idStudentAddress;
    }
    
    public void setIdStudentAddress(Long idStudentAddress) {
        this.idStudentAddress = idStudentAddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStudent")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="addressName", length=100)
    public String getAddressName() {
        return this.addressName;
    }
    
    public void setAddressName(String addressName) {
        this.addressName = addressName;
    }

    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="addressType")
    public Short getAddressType() {
        return this.addressType;
    }
    
    public void setAddressType(Short addressType) {
        this.addressType = addressType;
    }

    
    @Column(name="addressNumber")
    public Short getAddressNumber() {
        return this.addressNumber;
    }
    
    public void setAddressNumber(Short addressNumber) {
        this.addressNumber = addressNumber;
    }

    
    @Column(name="apartment")
    public Short getApartment() {
        return this.apartment;
    }
    
    public void setApartment(Short apartment) {
        this.apartment = apartment;
    }

    
    @Column(name="additionalInformation", length=100)
    public String getAdditionalInformation() {
        return this.additionalInformation;
    }
    
    public void setAdditionalInformation(String additionalInformation) {
        this.additionalInformation = additionalInformation;
    }

    
    @Column(name="reference", length=200)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="idDistrict")
    public Integer getIdDistrict() {
        return this.idDistrict;
    }
    
    public void setIdDistrict(Integer idDistrict) {
        this.idDistrict = idDistrict;
    }

    
    @Column(name="userCreated", length=100)
    public String getUserCreated() {
        return this.userCreated;
    }
    
    public void setUserCreated(String userCreated) {
        this.userCreated = userCreated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreated", length=19)
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }




}


